Formulário MGM
Onyo/onyo-mgm-register pull request #1
Opened 2020-11-25 13:46 UTC by dropecosta

Qual o contexto desse PR?:
Esse PR serve para fazer o primeiro release da atualização do formulário de cadastro do MGM _(member get member)_.

Link da(s) tarefa(s):
https://dev.azure.com/adquirencia/PedePronto/_sprints/taskboard/PedePronto%20Team/PedePronto/Sprint%204?workitem=10205

Checklist:
 O build está ok?
 Possui 0 ou 1 migração?
 Se tem migração, ela pode fazer rollback?
[X] Possui teste automatizado?
[X] O código foi validado em staging?

2020-11-25 19:50 UTC, komyg requested changes

2020-11-25 19:50 UTC, komyg commented on src/pages/validation/validation.spec.tsx
> +//   });
Remover código comentado.

2020-11-25 19:50 UTC, komyg commented on src/pages/validation/validation.tsx
> +  });
Essas configurações fazem parte do form, então acho que devem ser parte do componente que implementa o form em si.

2020-11-25 19:50 UTC, komyg commented on src/services/use-register/use-register.ts
> +        setMessage('Não foi possível cadastrar o usuário.');
Acho que a mensagem de erro pode ser um `useState` que é retornado pelo hook da mesma forma com fazemos com o `loading`. Da forma como está metade do estado é controlado pelo hook e a outra metadade pelo componente.

2020-11-25 19:50 UTC, komyg commented on src/services/use-update-register/use-update-register.ts
> +        setToken(response.data.token);
Em vez de usar o `setToken` gerado pelo `useState`, acho que você pode retornar o token como resultado do hook. Não acho que é uma boa idéia você declarar um estado em um componente e alterá-lo em outro (mesmo que seja um hook).

2020-11-25 19:50 UTC, komyg commented on src/services/use-validate-user/use-validate-user.ts
> +        setMessage('Não foi possível validar os dados.');
Acho que você deveria retornar um objeto de erro em vez de chamar o `setMessage` criado em um componente. Da forma como está hoje, metade do estado é gerido pelo hook e metade pelo componente.

2020-11-26 11:12 UTC, dropecosta commented on src/components/header/header.tsx
> +        <FormGroup>
Corrigido.

2020-11-26 11:15 UTC, dropecosta commented on src/pages/validation/validation.spec.tsx
> +//   });
Ok, removido.

2020-11-26 11:20 UTC, dropecosta commented on src/index.css
> +  font-family: 'Quicksand';
Corrigido, mantive a Roboto.

2020-11-26 11:23 UTC, dropecosta commented on src/config/global.config.ts
> +  }
Ok, alterado.

2020-11-26 12:24 UTC, dropecosta commented on src/components/toolbar/toolbar.tsx
> +        width='168'
Corrigido.

2020-11-26 13:28 UTC, dropecosta commented on src/index.tsx
> +  <ThemeProvider theme={theme}>
Alterado. Movi o tema para src/config/theme-provider.ts.

2020-11-26 14:14 UTC, dropecosta commented on src/pages/validation/validation.tsx
> +  });
Corrigido.

2020-11-26 14:18 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.tsx
> +}
Corrigido.

2020-11-26 14:22 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.spec.tsx
> +});
Corrigido.

2020-11-26 14:33 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.spec.tsx
> +const phoneEditionInitialValuesMock = { newDDD: '71', newTelephone: '992381591' };
Alterado para uma string vazia.
`const phoneEditionInitialValuesMock = { newDDD: '', newTelephone: '' };`

2020-11-26 14:39 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.tsx
> +      setDisabled(!disabled);
Corrigido.

2020-11-26 17:54 UTC, dropecosta commented on src/components/register-form/register-form.tsx
> +        <Box marginBottom={2}>
Corrigido.

2020-11-26 17:55 UTC, dropecosta commented on src/components/register-form/register-form.tsx
> +          <Typography className={classes.passwordSubtitle} variant='subtitle2'></Typography>
Corrigido.

2020-11-26 18:51 UTC, dropecosta commented on src/components/validation-form/validation-form.spec.tsx
> +});
Corrigido.

2020-11-26 18:51 UTC, dropecosta commented on src/components/validation-form/validation-form.tsx
> +  validationFormSchema: Yup.ObjectSchema;
Corrigido.

2020-11-27 13:13 UTC, dropecosta commented on src/services/use-register/use-register.ts
> +        setMessage('Não foi possível cadastrar o usuário.');
Corrigido.

2020-11-27 13:13 UTC, dropecosta commented on src/services/use-update-register/use-update-register.ts
> +        setToken(response.data.token);
Corrigido.

2020-11-27 13:13 UTC, dropecosta commented on src/services/use-validate-user/use-validate-user.ts
> +        setMessage('Não foi possível validar os dados.');
Corrigido.

2020-11-27 17:49 UTC, dropecosta commented on src/components/header/header.style.tsx
> +})(Button);
Como falamos, achei que ficou muito complexo, vou rever novamente depois.

2020-11-27 17:49 UTC, dropecosta commented on src/components/register-form/register-form.spec.tsx
> +});
Corrigido.

2020-11-27 17:50 UTC, dropecosta commented on src/components/register-form/register-form.spec.tsx
> +  });
Corrigido.

2020-11-27 17:54 UTC, dropecosta commented on src/services/use-validate-user/use-validate-user.ts
> +        setMessage('Não foi possível validar os dados.');
Corrigido.

2020-11-27 17:54 UTC, dropecosta commented on src/services/use-update-register/use-update-register.ts
> +        setToken(response.data.token);
Corrigido.

2020-11-27 17:54 UTC, dropecosta commented on src/services/use-register/use-register.ts
> +        setMessage('Não foi possível cadastrar o usuário.');
Corrigido.

2020-11-27 17:54 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.spec.tsx
> +const phoneEditionInitialValuesMock = { newDDD: '71', newTelephone: '992381591' };
Corrigido.

2020-11-30 18:52 UTC, komyg requested changes

2020-11-30 18:52 UTC, komyg commented on src/components/phone-edition-form/phone-edition-form.spec.tsx
>          phoneEditionInitialValues={phoneEditionInitialValuesMock}
Acho que os initial values também deve estar dentro do componente do formulário.

2020-11-30 18:52 UTC, komyg commented on src/components/phone-edition-form/phone-edition-form.tsx
>        initialValues={props.phoneEditionInitialValues}
Acho que os initial values também deve estar dentro do componente do formulário.

2020-11-30 18:52 UTC, komyg commented on src/components/validation-form/validation-form.tsx
>        initialValues={props.validationFormInitialValues}
Acho que os initial values também deve estar dentro do componente do formulário.

2020-11-30 18:52 UTC, komyg commented on src/pages/validation/validation.tsx
> +// import { object, string } from 'yup';
Remover código comentado.

2020-11-30 18:52 UTC, komyg commented on src/pages/validation/validation.tsx
> +  // });
Remover código comentado.

2020-11-30 18:52 UTC, komyg commented on src/pages/validation/validation.tsx
>              phoneEditionInitialValues={phoneEditionInitialValues}
Acho que os initial values também devem estar dentro do componente que contém o form.

2020-11-30 18:52 UTC, komyg commented on src/pages/validation/validation.tsx
> +        open={message !== undefined && message !== ''}
Aqui você pode testar por falsy, ou seja: `open={!message}`

2020-11-30 18:52 UTC, komyg commented on src/services/use-get-users/use-get-users.ts
> +  (setMessage: string): {
Não acho que você precisa inicializar essa variável aqui.

2020-11-30 18:52 UTC, komyg commented on src/services/use-get-users/use-get-users.spec.tsx
> -    expect(setMessageMock).toBeCalled();
Aqui você retirou a verificação da chamada para o `setMessage`, mas não verificou se a variável com mensagem de erro foi setada corretamente.

2020-11-30 18:52 UTC, komyg commented on src/pages/home/home.tsx
> +  const { user, referralCode } = useGetUsers('');
Você não está verificando a condição de erro aqui.

2020-11-30 18:52 UTC, komyg commented on src/pages/validation/validation.tsx
>    }, []);
Você não está verificando a condição de erro aqui. E a princípio você não precisa mais do estado `message`, pois ele já está dentro do hook.

2020-11-30 18:52 UTC, komyg commented on src/services/use-register/use-register.spec.tsx
> -    expect(setMessageMock).toBeCalled();
Aqui você não está verificando o retorno da mensagem de erro no hook.

2020-11-30 18:52 UTC, komyg commented on src/services/use-update-register/use-update-register.spec.tsx
> -    expect(setMessageMock).not.toBeCalled();
Aqui você não está verificando se a mensagem de erro que é retornada pelo hook foi setada.

2020-11-30 18:52 UTC, komyg commented on src/services/use-update-register/use-update-register.ts
> +export const useUpdateRegister: UseUpdateRegister = (setToken) => {
O token aqui também não deveria ser retornado como resultado do hook? Se não o estado fica dividido em dois.

2020-11-30 18:52 UTC, komyg commented on src/services/use-validate-user/use-validate-user.spec.tsx
> -    expect(setMessageMock).toBeCalled();
Aqui você não está verificando se a mensagem de erro retornada pelo hook está sendo setada.

2020-11-30 18:52 UTC, komyg commented on src/services/use-validate-user/use-validate-user.ts
> +  (setMessage: string): {
Você tem uma variável aqui (`setMessage`) que é sobreescrita logo abaixo pelo `useState`.

2020-11-30 19:54 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.spec.tsx
>          phoneEditionInitialValues={phoneEditionInitialValuesMock}
Não alterei, pois como falamos, esses valores vem setados após a submissão do register-form, não sendo criados dentro do componente. Criar o mock foi a solução para isolar o teste.

2020-11-30 19:57 UTC, dropecosta commented on src/components/phone-edition-form/phone-edition-form.tsx
>        initialValues={props.phoneEditionInitialValues}
Mesmo caso acima, esses valores já vem setados do componente pai.

2020-11-30 20:02 UTC, dropecosta commented on src/components/validation-form/validation-form.tsx
>        initialValues={props.validationFormInitialValues}
Eles estão, no mesmo componente:
```
interface Props {
  validationFormInitialValues: { validation: string };
  onSubmitValidationForm: (values: any) => void;
}
```

2020-11-30 20:03 UTC, dropecosta commented on src/pages/validation/validation.tsx
> +// import { object, string } from 'yup';
Corrigido.

2020-11-30 20:03 UTC, dropecosta commented on src/pages/validation/validation.tsx
> +  // });
Corrigido.

2020-11-30 20:05 UTC, dropecosta commented on src/pages/validation/validation.tsx
>              phoneEditionInitialValues={phoneEditionInitialValues}
Mesmo caso acima.

2020-11-30 20:08 UTC, dropecosta commented on src/pages/validation/validation.tsx
> +        open={message !== undefined && message !== ''}
Alterado.

2020-11-30 20:27 UTC, dropecosta commented on src/services/use-get-users/use-get-users.ts
> +  (setMessage: string): {
Alterado.

2020-11-30 23:37 UTC, dropecosta commented on src/pages/validation/validation.tsx
>              phoneEditionInitialValues={phoneEditionInitialValues}
Alterado.

2020-11-30 23:38 UTC, dropecosta commented on src/components/validation-form/validation-form.tsx
>        initialValues={props.validationFormInitialValues}
Alterado.

2020-12-14 14:05 UTC, komyg approved these changes

2020-12-14 22:13 UTC, merged